=== navikt/permittering-dokgen/content/templates/tiltak-avtale/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "tiltakstype",
    "avtaleId",
    "avtaleVersjonId",
    "deltakerFnr",
    "bedriftNr",
    "veilederNavIdent",
    "opprettet",
    "versjon",
    "deltakerFornavn",
    "deltakerEtternavn",
    "deltakerTlf",
    "bedriftNavn",
    "arbeidsgiverFornavn",
    "arbeidsgiverEtternavn",
    "arbeidsgiverTlf",
    "veilederFornavn",
    "veilederEtternavn",
    "veilederTlf",
    "oppfolging",
    "tilrettelegging",
    "startDato",
    "sluttDato",
    "stillingprosent",
    "godkjentAvDeltaker",
    "godkjentAvArbeidsgiver",
    "godkjentAvVeileder"
  ],
  "properties": {
    "tiltakstype": {
      "$id": "#/properties/tiltakstype",
      "type": "string",
      "enum": [
        "ARBEIDSTRENING",
        "MIDLERTIDIG_LONNSTILSKUDD",
        "VARIG_LONNSTILSKUDD",
        "MENTOR"
      ]
    },
    "avtaleId": {
      "$id": "#/properties/avtaleId",
      "type": "string",
      "title": "The Avtaleid Schema",
      "default": "",
      "examples": [
        "ca3d7189-0852-4693-a3dd-d518b4ec42e4"
      ],
      "pattern": "^(.*)$"
    },
    "avtaleVersjonId": {
      "$id": "#/properties/avtaleVersjonId",
      "type": "string",
      "title": "The Avtaleversjonid Schema",
      "default": "",
      "examples": [
        "878c49f4-7225-4bb7-becf-a63b90a1baf7"
      ],
      "pattern": "^(.*)$"
    },
    "deltakerFnr": {
      "$id": "#/properties/deltakerFnr",
      "type": "string",
      "title": "The Deltakerfnr Schema",
      "default": "",
      "examples": [
        "02018099999"
      ],
      "pattern": "^(.*)$"
    },
    "bedriftNr": {
      "$id": "#/properties/bedriftNr",
      "type": "string",
      "title": "The Bedriftnr Schema",
      "default": "",
      "examples": [
        "999988881"
      ],
      "pattern": "^(.*)$"
    },
    "veilederNavIdent": {
      "$id": "#/properties/veilederNavIdent",
      "type": "string",
      "title": "The Veiledernavident Schema",
      "default": "",
      "examples": [
        "X123456"
      ],
      "pattern": "^(.*)$"
    },
    "opprettet": {
      "$id": "#/properties/opprettet",
      "type": "string",
      "title": "The Opprettet Schema",
      "default": "",
      "examples": [
        "2019-09-09"
      ],
      "pattern": "^(.*)$"
    },
    "versjon": {
      "$id": "#/properties/versjon",
      "type": "integer",
      "title": "The Versjon Schema",
      "default": 0,
      "examples": [
        2
      ]
    },
    "deltakerFornavn": {
      "$id": "#/properties/deltakerFornavn",
      "type": "string",
      "title": "The Deltakerfornavn Schema",
      "default": "",
      "examples": [
        "Ronny"
      ],
      "pattern": "^(.*)$"
    },
    "deltakerEtternavn": {
      "$id": "#/properties/deltakerEtternavn",
      "type": "string",
      "title": "The Deltakeretternavn Schema",
      "default": "",
      "examples": [
        "Deltaker"
      ],
      "pattern": "^(.*)$"
    },
    "deltakerTlf": {
      "$id": "#/properties/deltakerTlf",
      "type": "string",
      "title": "The Deltakertlf Schema",
      "default": "",
      "examples": [
        "00000000"
      ],
      "pattern": "^(.*)$"
    },
    "bedriftNavn": {
      "$id": "#/properties/bedriftNavn",
      "type": "string",
      "title": "The Bedriftnavn Schema",
      "default": "",
      "examples": [
        "Hansen AS"
      ],
      "pattern": "^(.*)$"
    },
    "arbeidsgiverFornavn": {
      "$id": "#/properties/arbeidsgiverFornavn",
      "type": "string",
      "title": "The Arbeidsgiverfornavn Schema",
      "default": "",
      "examples": [
        "Ronnys"
      ],
      "pattern": "^(.*)$"
    },
    "arbeidsgiverEtternavn": {
      "$id": "#/properties/arbeidsgiverEtternavn",
      "type": "string",
      "title": "The Arbeidsgiveretternavn Schema",
      "default": "",
      "examples": [
        "Kremmer"
      ],
      "pattern": "^(.*)$"
    },
    "arbeidsgiverTlf": {
      "$id": "#/properties/arbeidsgiverTlf",
      "type": "string",
      "title": "The Arbeidsgivertlf Schema",
      "default": "",
      "examples": [
        "22334455"
      ],
      "pattern": "^(.*)$"
    },
    "veilederFornavn": {
      "$id": "#/properties/veilederFornavn",
      "type": "string",
      "title": "The Veilederfornavn Schema",
      "default": "",
      "examples": [
        "Jan-Ronny"
      ],
      "pattern": "^(.*)$"
    },
    "veilederEtternavn": {
      "$id": "#/properties/veilederEtternavn",
      "type": "string",
      "title": "The Veilederetternavn Schema",
      "default": "",
      "examples": [
        "Veileder"
      ],
      "pattern": "^(.*)$"
    },
    "veilederTlf": {
      "$id": "#/properties/veilederTlf",
      "type": "string",
      "title": "The Veiledertlf Schema",
      "default": "",
      "examples": [
        "33445566"
      ],
      "pattern": "^(.*)$"
    },
    "oppfolging": {
      "$id": "#/properties/oppfolging",
      "type": "string",
      "title": "The Oppfolging Schema",
      "default": "",
      "examples": [
        "Telefon hver uke"
      ],
      "pattern": "^([\\s\\S]*)$"
    },
    "tilrettelegging": {
      "$id": "#/properties/tilrettelegging",
      "type": "string",
      "title": "The Tilrettelegging Schema",
      "default": "",
      "examples": [
        "Ingen"
      ],
      "pattern": "^([\\s\\S]*)$"
    },
    "startDato": {
      "$id": "#/properties/startDato",
      "type": "string",
      "title": "The Startdato Schema",
      "default": "",
      "examples": [
        "2019-01-01"
      ],
      "pattern": "^(.*)$"
    },
    "sluttDato": {
      "$id": "#/properties/sluttDato",
      "type": "string",
      "title": "The Sluttdato Schema",
      "default": "",
      "examples": [
        "2019-02-02"
      ],
      "pattern": "^(.*)$"
    },
    "stillingprosent": {
      "$id": "#/properties/stillingprosent",
      "type": "integer",
      "title": "The Stillingprosent Schema",
      "default": 0,
      "examples": [
        100
      ]
    },
    "maal": {
      "$id": "#/properties/maal",
      "type": "array",
      "title": "The Maal Schema",
      "items": {
        "$id": "#/properties/maal/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "kategori",
          "beskrivelse"
        ],
        "properties": {
          "kategori": {
            "$id": "#/properties/maal/items/properties/kategori",
            "type": "string",
            "title": "The Kategori Schema",
            "default": "",
            "examples": [
              "FÅ_JOBB_I_BEDRIFTEN"
            ],
            "pattern": "^(.*)$"
          },
          "beskrivelse": {
            "$id": "#/properties/maal/items/properties/beskrivelse",
            "type": "string",
            "title": "The Beskrivelse Schema",
            "default": "",
            "examples": [
              "Målet med arbeidstreningen er og få opplæring i arbeidsoppgaver knyttet til sjåførjobb, lære bedriften og kjenne og får den opplæringen du trenger for og kunne tre inn i stillings funksjonen når du har fått førerkortet. Det foreligger bekreftelse på lovnad om jobb dersom kriteriene er oppfylt i forhold til krav om førerkort."
            ],
            "pattern": "^([\\s\\S]*)$"
          }
        }
      }
    },
    "oppgaver": {
      "$id": "#/properties/oppgaver",
      "type": "array",
      "title": "The Oppgaver Schema",
      "items": {
        "$id": "#/properties/oppgaver/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "tittel",
          "beskrivelse",
          "opplaering"
        ],
        "properties": {
          "tittel": {
            "$id": "#/properties/oppgaver/items/properties/tittel",
            "type": "string",
            "title": "The Tittel Schema",
            "default": "",
            "examples": [
              "Sjåføroppgaver"
            ],
            "pattern": "^(.*)$"
          },
          "beskrivelse": {
            "$id": "#/properties/oppgaver/items/properties/beskrivelse",
            "type": "string",
            "title": "The Beskrivelse Schema",
            "default": "",
            "examples": [
              "Vi skal lære henne bestille varer fra leverandører og besøker de slik hun få erfaring på det"
            ],
            "pattern": "^([\\s\\S]*)$"
          },
          "opplaering": {
            "$id": "#/properties/oppgaver/items/properties/opplaering",
            "type": "string",
            "title": "The Opplaering Schema",
            "default": "",
            "examples": [
              "Opplæring i kasse og kundebehandling"
            ],
            "pattern": "^([\\s\\S]*)$"
          }
        }
      }
    },
    "arbeidsoppgaver": {
      "$id": "#/properties/arbeidsoppgaver",
      "type": ["string", "null"],
      "title": "The Arbeidsoppgaver Schema",
      "default": "",
      "examples": [
        "Sjåføroppgaver"
      ],
      "pattern": "^([\\s\\S]*)$"
    },
    "godkjentPaVegneGrunn": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$id": "#/properties/godkjentPaVegneGrunn",
          "type": "object",
          "title": "The Godkjentpavegnegrunn Schema",
          "required": [
            "ikkeBankId",
            "reservert",
            "digitalKompetanse"
          ],
          "properties": {
            "ikkeBankId": {
              "$id": "#/properties/godkjentPaVegneGrunn/properties/ikkeBankId",
              "type": "boolean",
              "title": "The Ikkebankid Schema",
              "default": false,
              "examples": [
                true
              ]
            },
            "reservert": {
              "$id": "#/properties/godkjentPaVegneGrunn/properties/reservert",
              "type": "boolean",
              "title": "The Reservert Schema",
              "default": false,
              "examples": [
                false
              ]
            },
            "digitalKompetanse": {
              "$id": "#/properties/godkjentPaVegneGrunn/properties/digitalKompetanse",
              "type": "boolean",
              "title": "The Digitalkompetanse Schema",
              "default": false,
              "examples": [
                false
              ]
            }
          }
        }
      ]
    },
    "godkjentAvDeltaker": {
      "$id": "#/properties/godkjentAvDeltaker",
      "type": "string",
      "title": "The Godkjentavdeltaker Schema",
      "default": "",
      "examples": [
        "2019-09-09"
      ],
      "pattern": "^(.*)$"
    },
    "godkjentAvArbeidsgiver": {
      "$id": "#/properties/godkjentAvArbeidsgiver",
      "type": "string",
      "title": "The Godkjentavarbeidsgiver Schema",
      "default": "",
      "examples": [
        "2019-10-09"
      ],
      "pattern": "^(.*)$"
    },
    "godkjentAvVeileder": {
      "$id": "#/properties/godkjentAvVeileder",
      "type": "string",
      "title": "The Godkjentavveileder Schema",
      "default": "",
      "examples": [
        "2019-11-09"
      ],
      "pattern": "^(.*)$"
    },
    "godkjentPaVegneAv": {
      "$id": "#/properties/godkjentPaVegneAv",
      "type": "boolean",
      "title": "The Godkjentpavegneav Schema",
      "default": false,
      "examples": [
        true
      ]
    },
    "arbeidsgiverKontonummer": {
      "$id": "#/properties/arbeidsgiverKontonummer",
      "type": ["string", "null"],
      "title": "The arbeidsgiverKontonummer Schema",
      "default": "",
      "examples": [
        "11122233344"
      ]
    },
    "stillingstype": {
      "$id": "#/properties/stillingstype",
      "type": ["string", "null"],
      "title": "The stillingstype Schema",
      "default": "",
      "examples": [
        "Stilling"
      ]
    },
    "lonnstilskuddProsent": {
      "$id": "#/properties/lonnstilskuddProsent",
      "type": ["integer", "null"],
      "title": "The lonnstilskuddProsent Schema",
      "default": false,
      "examples": [
        40
      ]
    },
    "manedslonn": {
      "$id": "#/properties/manedslonn",
      "type": ["integer", "null"],
      "title": "The manedslonn Schema",
      "examples": [
        10000
      ]
    },
    "feriepengesats": {
      "$id": "#/properties/feriepengesats",
      "type": ["number", "null"],
      "title": "The feriepengesats Schema",
      "default": false,
      "examples": [
        10.2
      ]
    },
    "arbeidsgiveravgift": {
      "$id": "#/properties/arbeidsgiveravgift",
      "type": ["number", "null"],
      "title": "The arbeidsgiveravgift Schema",
      "examples": [
        14.1
      ]
    },
    "mentorFornavn": {
      "$id": "#/properties/mentorFornavn",
      "type": ["string", "null"],
      "title": "The Mentorfornavn Schema",
      "default": "",
      "examples": [
        "Mia"
      ],
      "pattern": "^(.*)$"
    },
    "mentorEtternavn": {
      "$id": "#/properties/mentorEtternavn",
      "type": ["string", "null"],
      "title": "The mentor etternavn Schema",
      "default": "",
      "examples": [
        "Monsen"
      ],
      "pattern": "^(.*)$"
    },
    "mentorOppgaver": {
      "$id": "#/properties/mentorOppgaver",
      "type": ["string", "null"],
      "title": "The mentor oppgaver Schema",
      "examples": [
        "Ta imot deltaker"
      ],
      "pattern": "^([\\s\\S]*)$"
    },
    "mentorAntallTimer": {
      "$id": "#/properties/mentorAntallTimer",
      "type": ["integer", "null"],
      "title": "The mentor antall timer Schema",
      "examples": [
        40
      ]
    },
    "mentorTimelonn": {
      "$id": "#/properties/mentorTimelonn",
      "type": ["integer", "null"],
      "title": "The mentor timelønn Schema",
      "examples": [
        300
      ]
    }
  }
}

=== navikt/permittering-dokgen/content/templates/tiltak-avtale/testdata/arbeidstrening.json
{
  "tiltakstype": "ARBEIDSTRENING",
  "avtaleId": "ca3d7189-0852-4693-a3dd-d518b4ec42e4",
  "avtaleVersjonId": "878c49f4-7225-4bb7-becf-a63b90a1baf7",
  "deltakerFnr": "02018099999",
  "bedriftNr": "999988881",
  "veilederNavIdent": "X123456",
  "opprettet": "2019-09-09",
  "versjon": 2,
  "deltakerFornavn": "Ronny",
  "deltakerEtternavn": "Deltaker",
  "deltakerTlf": "00000000",
  "bedriftNavn": "Hansen AS",
  "arbeidsgiverFornavn": "Ronnys",
  "arbeidsgiverEtternavn": "Kremmer",
  "arbeidsgiverTlf": "22334455",
  "veilederFornavn": "Jan-Ronny",
  "veilederEtternavn": "Veileder",
  "veilederTlf": "33445566",
  "oppfolging": "Telefon hver uke",
  "tilrettelegging": "Ingen",
  "startDato": "2019-01-01",
  "sluttDato": "2019-02-02",
  "stillingprosent": 100,
  "maal": [
    {
      "kategori": "Få jobb i bedriften",
      "beskrivelse": "Målet med arbeidstreningen er og få opplæring i arbeidsoppgaver knyttet til sjåførjobb, lære bedriften og kjenne og får den opplæringen du trenger for og kunne tre inn i stillings funksjonen når du har fått førerkortet. Det foreligger bekreftelse på lovnad om jobb dersom kriteriene er oppfylt i forhold til krav om førerkort."
    }
  ],
  "arbeidsoppgaver": "- Lagerarbeid\nBeskrivelse: Rydde på lageret\nOpplæring: Ryddekurs\n\n- Lagerarbeid\nBeskrivelse: Rydde på lageret\nOpplæring: Ryddekurs\n\n- Lagerarbeid\nBeskrivelse: Rydde på lageret\nOpplæring: Ryddekurs",
  "godkjentPaVegneGrunn": {
    "ikkeBankId": true,
    "digitalKompetanse": true,
    "reservert": true
  },
  "godkjentAvDeltaker": "2019-09-09",
  "godkjentAvArbeidsgiver": "2019-10-09",
  "godkjentAvVeileder": "2019-11-09",
  "godkjentPaVegneAv": true
}

=== navikt/permittering-dokgen/content/templates/tiltak-avtale/testdata/mentor.json
{
  "tiltakstype": "MENTOR",
  "avtaleId": "0163f4a6-6927-440b-9e1d-0197090c5336",
  "avtaleVersjonId": "fb8461e5-fb0c-49cf-b349-530c0a086c93",
  "deltakerFnr": "00000000000",
  "bedriftNr": "990983666",
  "veilederNavIdent": "Z992785",
  "opprettet": "2020-02-11",
  "deltakerFornavn": "Jo",
  "deltakerEtternavn": "Å",
  "deltakerTlf": "777788888",
  "bedriftNavn": "NAV IKT",
  "arbeidsgiverFornavn": "Hans",
  "arbeidsgiverEtternavn": "Hansen",
  "arbeidsgiverTlf": "22222222",
  "veilederFornavn": "Bjarte",
  "veilederEtternavn": "Nilsen",
  "veilederTlf": "55555555",
  "oppfolging": "Følge opp",
  "tilrettelegging": "Legge til rette",
  "stillingprosent": 60,
  "versjon": 1,
  "mentorFornavn": "Sindre",
  "mentorEtternavn": "Løken",
  "mentorOppgaver": "Veilede",
  "mentorAntallTimer": 30,
  "mentorTimelonn": 400,
  "godkjentPaVegneGrunn": null,
  "arbeidsgiverKontonummer": null,
  "stillingstype": null,
  "arbeidsoppgaver": null,
  "lonnstilskuddProsent": null,
  "manedslonn": null,
  "feriepengesats": null,
  "arbeidsgiveravgift": null,
  "sluttDato": "2020-02-29",
  "startDato": "2020-02-11",
  "maal": [],
  "oppgaver": [],
  "godkjentAvDeltaker": "2020-02-11",
  "godkjentAvArbeidsgiver": "2020-02-11",
  "godkjentAvVeileder": "2020-02-11",
  "godkjentPaVegneAv": false
}

=== navikt/permittering-dokgen/content/templates/tiltak-avtale/testdata/lønnstilskudd.json
{
  "tiltakstype": "MIDLERTIDIG_LONNSTILSKUDD",
  "avtaleId": "ca3d7189-0852-4693-a3dd-d518b4ec42e4",
  "avtaleVersjonId": "878c49f4-7225-4bb7-becf-a63b90a1baf7",
  "deltakerFnr": "02018099999",
  "bedriftNr": "999988881",
  "veilederNavIdent": "X123456",
  "opprettet": "2019-09-09",
  "versjon": 2,
  "deltakerFornavn": "Ronny",
  "deltakerEtternavn": "Deltaker",
  "deltakerTlf": "00000000",
  "bedriftNavn": "Hansen AS",
  "arbeidsgiverFornavn": "Ronnys",
  "arbeidsgiverEtternavn": "Kremmer",
  "arbeidsgiverTlf": "22334455",
  "veilederFornavn": "Jan-Ronny",
  "veilederEtternavn": "Veileder",
  "veilederTlf": "33445566",
  "oppfolging": "Telefon hver uke",
  "tilrettelegging": "Ingen",
  "startDato": "2019-01-01",
  "sluttDato": "2019-02-02",
  "stillingprosent": 100,
  "godkjentPaVegneGrunn": null,
  "godkjentAvDeltaker": "2019-09-09",
  "godkjentAvArbeidsgiver": "2019-10-09",
  "godkjentAvVeileder": "2019-11-09",
  "godkjentPaVegneAv": false,
  "arbeidsgiverKontonummer": "11122233344",
  "stillingstype": "Stilling",
  "arbeidsoppgaver": "- Lagerarbeid\nBeskrivelse: Rydde på lageret\nOpplæring: Ryddekurs\n\n- Lagerarbeid\nBeskrivelse: Rydde på lageret\nOpplæring: Ryddekurs\n\n- Lagerarbeid\nBeskrivelse: Rydde på lageret\nOpplæring: Ryddekurs",
  "lonnstilskuddProsent": 40,
  "manedslonn": 10000,
  "feriepengesats": 10.2,
  "arbeidsgiveravgift": 14.1
}
